/**
 * End-to-end tests of the Kavach loop against the offline mock backend, plus unit tests of the
 * Snowflake REST plumbing that cannot be exercised live here (value conversion, JWT claims, polling).
 * Ported from tests/test_kavach.py and extended.
 */
import { createHash, generateKeyPairSync, verify } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import * as path from 'node:path';

import type { CompletionResult } from '../src/kavach/backends/backend.interface';
import { MockBackend, verifiedSql, canonicalJson } from '../src/kavach/backends/mock.backend';
import { buildKeypairJwt, jwtAccount, resolveSnowflakeAuth, type SnowflakeAuth } from '../src/kavach/backends/snowflake-auth';
import { parseAnalystResponse, SnowflakeBackend, toAuditReceipt, toSearchHit } from '../src/kavach/backends/snowflake.backend';
import { convertValue, SqlApiClient, toBindings, toTable, type RowTypeField } from '../src/kavach/backends/sql-api';
import * as config from '../src/kavach/config';
import type { AskResult, DataEvidence, PolicyEvidence } from '../src/kavach/contract';
import { parseCsv } from '../src/kavach/csv';
import {
  expandQuery, fallbackAnswer, heuristicRoute, isReadOnlySql, KavachOrchestrator,
} from '../src/kavach/orchestrator.service';
import { stem } from '../src/kavach/text';

const Q = config.DEMO_QUESTIONS.map((d) => d.question);
const ids = (r: AskResult): string[] => (r.policy?.chunks ?? []).map((c) => c.chunkId);

describe('semantic model', () => {
  it('parses the verified queries and maps __table to physical names', () => {
    const sql = verifiedSql(readFileSync(config.SEMANTIC_MODEL_PATH, 'utf8'));
    const names = Object.keys(sql);
    for (const n of ['early_delinquency_exposure', 'structuring_this_week', 'ntc_income_mismatch_30d', 'open_alerts_by_rule',
      'gnpa_by_product', 'early_delinquency_by_partner', 'high_risk_kyc_overdue']) {
      expect(names).toContain(n);
    }
    expect(sql.structuring_this_week.sql).toContain('FROM KAVACH.CORE.STRUCTURING_SIGNALS AS s');
    expect(sql.structuring_this_week.sql).not.toMatch(/__\w+/);
    expect(isReadOnlySql(sql.early_delinquency_exposure.sql)).toBe(true);
  });
});

describe('router', () => {
  it.each([
    [Q[0], 'DATA'], [Q[1], 'BOTH'], [Q[2], 'DATA'], [Q[3], 'POLICY'],
  ])('%s -> %s', (q, route) => {
    expect(heuristicRoute(q).route).toBe(route);
  });

  it('splits a BOTH question and carries the subject into the policy query', () => {
    const r = heuristicRoute(Q[1]);
    expect(r.dataQuestion).toBe('Show me accounts flagged for structuring this week');
    expect(r.policyQueries).toEqual(['what does our AML policy require us to do about them? structuring']);
  });

  it('decomposes an SBR question into layer classification + governance + disclosure sub-queries', () => {
    const r = heuristicRoute(Q[3]);
    expect(r.policyQueries).toHaveLength(3);
    expect(r.policyQueries[0]).toMatch(/^layer classification/);
    expect(r.policyQueries[1]).toMatch(/^governance requirements/);
    expect(r.policyQueries[2]).toMatch(/^disclosure requirements/);
  });

  it('expands glossary terms (prefix match at a word boundary)', () => {
    const e = expandQuery('structuring alerts');
    expect(e).toContain('smurfing');
    expect(e).toContain('FIU-IND'); // "str" is a prefix of "structuring", as in the Python reference
    expect(expandQuery('nothing relevant')).toBe('nothing relevant');
  });

  it('uses the LLM router when a model is available', async () => {
    class LlmMock extends MockBackend {
      override async complete(prompt: string): Promise<CompletionResult> {
        if (prompt.startsWith('You are the router')) {
          return { text: 'Sure: {"route": "policy", "reason": "asks about rules", "data_question": "", "policy_queries": ["STR timeline", "tipping off"]}', model: 'm1' };
        }
        return { text: null, model: null };
      }
    }
    const kv = new KavachOrchestrator(new LlmMock());
    const r = await kv.route('When must we file an STR?');
    expect(r).toMatchObject({ route: 'POLICY', router: 'llm', policyQueries: ['STR timeline', 'tipping off'] });
  });
});

describe('read-only SQL guard', () => {
  it('accepts a single SELECT / WITH and rejects anything else', () => {
    expect(isReadOnlySql('-- Generated by Cortex Analyst\nWITH x AS (SELECT 1) SELECT * FROM x;')).toBe(true);
    expect(isReadOnlySql('/* c */ select 1')).toBe(true);
    expect(isReadOnlySql('SELECT 1; DROP TABLE KAVACH.CORE.ACCOUNTS')).toBe(false);
    expect(isReadOnlySql('DELETE FROM KAVACH.GOV.AUDIT_LOG')).toBe(false);
    expect(isReadOnlySql('')).toBe(false);
  });
});

describe('ask flow (offline mock)', () => {
  const b = new MockBackend(undefined, undefined, 0);
  const kv = new KavachOrchestrator(b);

  it('Q1 early delinquency: all DPD > 60, >= 14 rows, total exposure, HIGH confidence', async () => {
    const res = await kv.ask(Q[0], 'tester');
    expect(res.route).toBe('DATA');
    expect(res.policy).toBeNull();
    expect(res.data!.rowCount).toBeGreaterThanOrEqual(14);
    expect(res.data!.rows.every((r) => (r.DPD as number) > 60)).toBe(true);
    expect(typeof res.data!.rows[0].TOTAL_EXPOSURE).toBe('number');
    expect(res.data!.verifiedQueryUsed).toBe(true);
    expect(res.confidence.level).toBe('HIGH');
    expect(res.answer).toContain('[D1]');
    expect(res.answer).toMatch(/total exposure .*Rs [\d,]+/i);
    expect(res.model).toBe('deterministic-fallback');
    expect(res.steps.map((s) => [s.key, s.status])).toEqual([
      ['route', 'done'], ['analyst', 'done'], ['search', 'skipped'], ['synthesis', 'done'], ['audit', 'done'],
    ]);
  });

  it('Q2 structuring + AML policy: BOTH, 3 rows and the right clauses; finding links to the question record', async () => {
    const res = await kv.ask(Q[1], 'tester');
    expect(res.route).toBe('BOTH');
    expect(res.data!.rowCount).toBe(3);
    const top = ids(res);
    expect(top).toHaveLength(6);
    for (const id of ['SOP-AML-1.1', 'SOP-AML-2.2', 'SOP-AML-2.3', 'RBI-KYC-3.2', 'RBI-KYC-4.1']) expect(top).toContain(id);
    expect(res.answer).toContain('**Required actions**');
    expect(res.answer).toMatch(/within five working days/);
    expect(res.confidence.level).not.toBe('LOW');
    const f = await kv.generateFinding(res, 'CASE_NOTE', 'tester');
    expect(f.markdown).toContain('DRAFT - pending human review');
    expect(f.markdown).toContain('```sql');
    expect(f.markdown).toContain('## Reviewer sign-off');
    expect(f.markdown).toContain('### Applicable obligations');
    expect(f.findingId).toMatch(/^KVF-\d{8}-[0-9A-F]{6}$/);
    expect(f.audit.prevHash).toBe(res.audit.rowHash);
    expect(f.sourceAuditSeq).toBe(res.audit.auditSeq);
  });

  it('Q3 income mismatch: 6 first-time borrowers, 2 without an alert', async () => {
    const res = await kv.ask(Q[2], 'tester');
    expect(res.data!.rowCount).toBe(6);
    expect(res.data!.rows.filter((r) => r.HAS_INCOME_ALERT === 'NO')).toHaveLength(2);
    expect(res.answer).toMatch(/\*\*2\*\* of these/);
  });

  it('Q4 SBR (policy only): Middle Layer clause plus governance / disclosure clauses', async () => {
    const res = await kv.ask(Q[3], 'tester');
    expect(res.route).toBe('POLICY');
    expect(res.data).toBeNull();
    expect(res.policy!.queries).toHaveLength(3);
    const top = ids(res);
    expect(top).toContain('RBI-SBR-1.3');
    expect(['RBI-SBR-3.2', 'RBI-SBR-3.3', 'RBI-SBR-3.4', 'RBI-SBR-4.1'].filter((x) => top.includes(x)).length).toBeGreaterThanOrEqual(2);
    expect(res.policy!.chunks.every((c) => c.docId === 'RBI-SBR')).toBe(true);
    expect(res.policy!.chunks.map((c) => c.label)).toEqual(['P1', 'P2', 'P3', 'P4', 'P5', 'P6']);
  });

  it('an unanswerable question gets LOW confidence', async () => {
    const res = await kv.ask('Which accounts have the prettiest logos?', 'tester');
    expect(res.confidence.level).toBe('LOW');
    expect(res.data!.error).toMatch(/did not generate SQL/);
  });

  it('keeps an audit trail with the right payload shape', async () => {
    const res = await kv.ask(Q[0], 'auditor');
    const p = await b.auditPayload(res.audit.auditSeq);
    expect(p).toMatchObject({ question: Q[0], route: 'DATA', model: 'deterministic-fallback', app_version: config.APP_VERSION });
    expect((p!.data as { row_count: number }).row_count).toBe(res.data!.rowCount);
    expect((p!.data as { sample_rows: unknown[] }).sample_rows).toHaveLength(10);
    expect(kv.getResult(res.id)).toBe(res);
  });

  it('hash chain verifies, and editing a stored payload is detected', async () => {
    const status = await b.chainStatus();
    expect(status.rows).toBeGreaterThan(0);
    expect(status.valid).toBe(status.rows);
    const rows = await b.auditLog(100);
    expect(rows[0].prevHash).toBe(rows[1].rowHash);
    // tamper with the stored route of the first record
    b.log[0].canon = b.log[0].canon.replace('"route":"DATA"', '"route":"POLICY"');
    const after = await b.chainStatus();
    expect(after.valid).toBe(after.rows - 1);
    expect((await b.auditLog(1000)).find((r) => r.auditSeq === 1)!.isValid).toBe(false);
  });

  it('breaking the linkage (deleting a record) is detected too', async () => {
    const b2 = new MockBackend(undefined, undefined, 0);
    for (let i = 0; i < 3; i++) await b2.logEvent('TEST', 'u', { i });
    b2.log.splice(1, 1);
    const s = await b2.chainStatus();
    expect(s).toEqual({ rows: 2, valid: 1 });
  });
});

describe('findings register and maker-checker review', () => {
  it('records the decision and flags self-review', async () => {
    const kv = new KavachOrchestrator(new MockBackend(undefined, undefined, 0));
    const res = await kv.ask(Q[1], 'maker');
    const f = await kv.generateFinding(res, 'STR_DRAFT', 'maker');
    expect(f.label).toBe(config.FINDING_TYPES.STR_DRAFT);
    await kv.reviewFinding(f.findingId, 'APPROVED', 'ok', 'checker');
    let row = (await kv.backend.findings()).find((r) => r.findingId === f.findingId)!;
    expect(row).toMatchObject({ status: 'APPROVED', makerCheckerOk: true, reviewer: 'checker', reviewComment: 'ok', createdBy: 'maker' });

    const f2 = await kv.generateFinding(res, 'EXCEPTION_REPORT', 'maker');
    const receipt = await kv.reviewFinding(f2.findingId, 'NEEDS_CHANGES', 'self review', 'maker');
    expect(receipt.auditSeq).toBeGreaterThan(f2.audit.auditSeq);
    row = (await kv.backend.findings()).find((r) => r.findingId === f2.findingId)!;
    expect(row).toMatchObject({ status: 'NEEDS_CHANGES', makerCheckerOk: false });
    const payload = await kv.backend.auditPayload(receipt.auditSeq);
    expect(payload).toMatchObject({ finding_id: f2.findingId, decision: 'NEEDS_CHANGES', maker_checker_ok: false });

    await expect(kv.reviewFinding('KVF-00000000-NOPE00', 'APPROVED', '', 'checker')).rejects.toThrow(/Unknown finding/);
  });
});

describe('confidence assessment', () => {
  const data: DataEvidence = {
    question: 'q', analystText: '', sql: 'SELECT 1', verifiedQueryUsed: true, columns: ['A'], rows: [{ A: 1 }], rowCount: 1,
    truncated: false, error: null, suggestions: [],
  };
  const policy: PolicyEvidence = {
    queries: ['q'], error: null,
    chunks: [{
      label: 'P1', chunkId: 'X-1', docId: 'X', docTitle: 'X', docType: 'SOP', issuer: 'i', version: 'v', sourceRef: 's',
      sectionId: '1', sectionTitle: 't', sectionPath: 'p', chunkText: 'text', disclaimer: '', score: null, lexicalCoverage: 0.8,
    }],
  };

  it('HIGH when verified data and well-covered passages are cited', () => {
    expect(KavachOrchestrator.assess(data, policy, 'Fact [D1]. Rule [P1].').level).toBe('HIGH');
  });
  it('LOW when the answer cites evidence that does not exist', () => {
    const c = KavachOrchestrator.assess(data, policy, 'Fact [D1]. Rule [P7].');
    expect(c.level).toBe('LOW');
    expect(c.reasons.join(' ')).toMatch(/does not exist: P7/);
  });
  it('LOW when the answer has no citations at all', () => {
    expect(KavachOrchestrator.assess(data, policy, 'Trust me.').level).toBe('LOW');
  });
  it('MEDIUM for generated (unverified) SQL; LOW on weak cosine similarity', () => {
    expect(KavachOrchestrator.assess({ ...data, verifiedQueryUsed: false }, null, 'x [D1]').level).toBe('MEDIUM');
    const weak = { ...policy, chunks: [{ ...policy.chunks[0], score: 0.1 }] };
    expect(KavachOrchestrator.assess(null, weak, 'x [P1]').level).toBe('LOW');
  });
  it('fallback answer only cites evidence that exists', () => {
    const a = fallbackAnswer('q', data, policy);
    expect(KavachOrchestrator.assess(data, policy, a).reasons.join(' ')).not.toMatch(/does not exist/);
  });
});

describe('text + csv helpers', () => {
  it('stems common inflections together', () => {
    expect(stem('structuring')).toBe(stem('structured'));
    expect(stem('deposits')).toBe(stem('deposit'));
    expect(stem('requirements')).toBe(stem('required'));
  });
  it('parses RFC 4180 CSV (quotes, embedded commas / newlines, "" escapes, CRLF)', () => {
    const rows = parseCsv('a,b,c\r\n1,"x, y","he said ""hi"""\r\n2,"multi\nline",\n');
    expect(rows).toEqual([['a', 'b', 'c'], ['1', 'x, y', 'he said "hi"'], ['2', 'multi\nline', '']]);
  });
  it('canonical JSON sorts keys recursively', () => {
    expect(canonicalJson({ b: 1, a: { d: [1, { z: 1, y: 2 }], c: null } })).toBe('{"a":{"c":null,"d":[1,{"y":2,"z":1}]},"b":1}');
  });
});

// ----------------------------------------------------------------------------- Snowflake REST plumbing
describe('SQL API value conversion', () => {
  const rowType: RowTypeField[] = [
    { name: 'ACCOUNT_ID', type: 'text' },
    { name: 'DPD', type: 'fixed', scale: 0, precision: 5 },
    { name: 'OUTSTANDING_PRINCIPAL', type: 'fixed', scale: 2, precision: 14 },
    { name: 'RATIO', type: 'real' },
    { name: 'NPA_FLAG', type: 'boolean' },
    { name: 'DISBURSAL_DATE', type: 'date' },
    { name: 'TXN_TS', type: 'timestamp_ntz' },
    { name: 'TS_LTZ', type: 'timestamp_ltz' },
    { name: 'TS_TZ', type: 'timestamp_tz' },
    { name: 'T', type: 'time' },
    { name: 'RECEIPT', type: 'variant' },
    { name: 'TAGS', type: 'array' },
  ];
  const data = [[
    'LA0000001', '120', '345000.50', '0.42', 'true', '20725', '1790701200.000000000', '1790701200.123000000',
    '1790701200.000000000 1770', '3723.5', '{"audit_seq":7,"row_hash":"ab"}', '["x","y"]',
  ], ['LA0000002', null, null, null, 'false', null, null, null, null, null, null, null]];

  it('converts by rowType', () => {
    const t = toTable(rowType, data);
    expect(t.columns).toEqual(rowType.map((f) => f.name));
    expect(t.rows[0]).toEqual({
      ACCOUNT_ID: 'LA0000001', DPD: 120, OUTSTANDING_PRINCIPAL: 345000.5, RATIO: 0.42, NPA_FLAG: true,
      DISBURSAL_DATE: '2026-09-29', TXN_TS: '2026-09-29T17:00:00', TS_LTZ: '2026-09-29T17:00:00.123Z',
      TS_TZ: '2026-09-29T22:30:00+05:30', T: '01:02:03.500', RECEIPT: { audit_seq: 7, row_hash: 'ab' }, TAGS: ['x', 'y'],
    });
    expect(t.rows[1]).toMatchObject({ DPD: null, NPA_FLAG: false, DISBURSAL_DATE: null, RECEIPT: null });
  });
  it('handles negative UTC offsets and bare values', () => {
    expect(convertValue('0.000000000 960', { name: 'X', type: 'timestamp_tz' })).toBe('1969-12-31T16:00:00-08:00');
    expect(convertValue('0', { name: 'X', type: 'date' })).toBe('1970-01-01');
    expect(convertValue('abc', { name: 'X', type: 'text' })).toBe('abc');
  });
  it('builds typed bindings', () => {
    expect(toBindings(['a', 3, 1.5, true, null])).toEqual({
      1: { type: 'TEXT', value: 'a' }, 2: { type: 'FIXED', value: '3' }, 3: { type: 'REAL', value: '1.5' },
      4: { type: 'BOOLEAN', value: 'true' }, 5: { type: 'TEXT', value: null },
    });
  });
});

describe('SQL API client (fake fetch)', () => {
  const auth: SnowflakeAuth = { mode: 'PAT', host: 'acct.snowflakecomputing.com', headers: async () => ({ Authorization: 'Bearer t' }) };
  const json = (status: number, body: unknown): Response => new Response(JSON.stringify(body), { status });

  it('polls 202 and stitches partitions together', async () => {
    const calls: { url: string; method: string; body?: unknown }[] = [];
    const responses = [
      json(202, { statementHandle: 'h1', statementStatusUrl: '/api/v2/statements/h1' }),
      json(200, {
        statementHandle: 'h1', data: [['1']],
        resultSetMetaData: { rowType: [{ name: 'N', type: 'fixed' }], partitionInfo: [{ rowCount: 1 }, { rowCount: 2 }] },
      }),
      json(200, { data: [['2'], ['3']] }),
    ];
    const fakeFetch = (async (url: string, init: RequestInit) => {
      calls.push({ url, method: String(init.method), body: init.body ? JSON.parse(String(init.body)) : undefined });
      return responses.shift()!;
    }) as unknown as typeof fetch;
    const c = new SqlApiClient(auth, { database: 'KAVACH', warehouse: 'KAVACH_WH', role: 'KAVACH_APP', timeoutS: 60, fetchImpl: fakeFetch });
    const t = await c.execute('SELECT n FROM t WHERE x = ?', ['a']);
    expect(t.rows.map((r) => r.N)).toEqual([1, 2, 3]);
    expect(calls[0].url).toMatch(/^https:\/\/acct\.snowflakecomputing\.com\/api\/v2\/statements\?requestId=/);
    expect(calls[0].body).toMatchObject({
      statement: 'SELECT n FROM t WHERE x = ?', timeout: 60, database: 'KAVACH', warehouse: 'KAVACH_WH', role: 'KAVACH_APP',
      bindings: { 1: { type: 'TEXT', value: 'a' } },
    });
    expect(calls[1]).toMatchObject({ method: 'GET', url: 'https://acct.snowflakecomputing.com/api/v2/statements/h1' });
    expect(calls[2].url).toBe('https://acct.snowflakecomputing.com/api/v2/statements/h1?partition=1');
  });

  it('wraps Analyst SQL, falls back across models and maps receipts', async () => {
    const statements: string[] = [];
    const fakeFetch = (async (_url: string, init: RequestInit) => {
      const body = JSON.parse(String(init.body)) as { statement: string; bindings?: Record<string, { value: string }> };
      statements.push(body.statement);
      if (body.statement.includes('CORTEX.COMPLETE')) {
        if (body.bindings!['1'].value !== 'llama3.1-70b') return json(422, { message: 'model unavailable' });
        return json(200, { resultSetMetaData: { rowType: [{ name: 'R', type: 'object' }] }, data: [[JSON.stringify({ choices: [{ messages: 'hello [D1]' }] })]] });
      }
      if (body.statement.startsWith('CALL')) {
        return json(200, { resultSetMetaData: { rowType: [{ name: 'LOG_EVENT', type: 'variant' }] }, data: [[JSON.stringify({ audit_seq: 5, event_id: 'e', row_hash: 'r', prev_hash: 'p', event_ts_utc: '2026-09-29 10:00:00' })]] });
      }
      return json(200, { resultSetMetaData: { rowType: [{ name: 'X', type: 'fixed' }] }, data: [['1']] });
    }) as unknown as typeof fetch;
    const b = new SnowflakeBackend(auth, { fetchImpl: fakeFetch });
    const out = await b.complete('hi');
    expect(out).toEqual({ text: 'hello [D1]', model: 'llama3.1-70b' });
    statements.length = 0;
    await b.complete('again'); // cached model: one call only
    expect(statements).toHaveLength(1);
    await b.runSql('SELECT 1 AS X', 5001);
    expect(statements[1]).toBe('SELECT * FROM (\nSELECT 1 AS X\n) LIMIT 5001');
    // Cortex Analyst ends with a comment line, then ";" on its own line
    await b.runSql('SELECT 2 AS X\n -- Generated by Cortex Analyst (request_id: r)\n;', 10);
    expect(statements[2]).toBe('SELECT * FROM (\nSELECT 2 AS X\n -- Generated by Cortex Analyst (request_id: r)\n) LIMIT 10');
    await expect(b.runSql('DELETE FROM t', 10)).rejects.toThrow(/read-only/);
    expect(await b.logEvent('T', 'u', { a: 1 })).toEqual({ auditSeq: 5, eventId: 'e', rowHash: 'r', prevHash: 'p', eventTsUtc: '2026-09-29 10:00:00' });
  });

  it('parses Analyst and Search responses', () => {
    const a = parseAnalystResponse({
      request_id: 'r1',
      message: { content: [
        { type: 'text', text: 'This is our interpretation' },
        { type: 'sql', statement: 'SELECT 1', confidence: { verified_query_used: { name: 'q' } } },
        { type: 'suggestions', suggestions: ['a', 'b'] },
      ] },
    });
    expect(a).toEqual({ text: 'This is our interpretation', sql: 'SELECT 1', verifiedQueryUsed: true, suggestions: ['a', 'b'], requestId: 'r1' });
    const h = toSearchHit({ chunk_id: 'C', doc_id: 'D', section_path: 'p', chunk_text: 't', '@scores': { cosine_similarity: 0.61 } });
    expect(h).toMatchObject({ chunkId: 'C', docId: 'D', sectionPath: 'p', chunkText: 't', score: 0.61 });
    expect(toSearchHit({ chunk_id: 'C' }).score).toBeNull();
    expect(toAuditReceipt('{"audit_seq": 3}').auditSeq).toBe(3);
  });
});

describe('key-pair JWT', () => {
  it('builds RS256 claims with the SPKI fingerprint and verifies with the public key', () => {
    const { privateKey, publicKey } = generateKeyPairSync('rsa', { modulusLength: 2048 });
    const pem = privateKey.export({ type: 'pkcs8', format: 'pem' }).toString();
    const now = Date.UTC(2026, 8, 29, 12, 0, 0);
    const jwt = buildKeypairJwt({ account: 'xy12345.eu-central-1', user: 'kavach_svc', privateKey: pem, nowMs: now });
    const fp = createHash('sha256').update(publicKey.export({ type: 'spki', format: 'der' })).digest('base64');
    expect(jwt.claims).toEqual({
      iss: `XY12345.KAVACH_SVC.SHA256:${fp}`, sub: 'XY12345.KAVACH_SVC', iat: now / 1000, exp: now / 1000 + 59 * 60,
    });
    const [h, p, s] = jwt.token.split('.');
    expect(JSON.parse(Buffer.from(h, 'base64url').toString())).toEqual({ alg: 'RS256', typ: 'JWT' });
    expect(JSON.parse(Buffer.from(p, 'base64url').toString())).toEqual(jwt.claims);
    expect(verify('RSA-SHA256', Buffer.from(`${h}.${p}`), publicKey, Buffer.from(s, 'base64url'))).toBe(true);
    expect(jwtAccount('myorg-myacct')).toBe('MYORG-MYACCT');
  });

  it('resolves auth modes from the environment in priority order', async () => {
    const none = '/nonexistent/token';
    expect(resolveSnowflakeAuth({}, none)).toBeNull();
    const pat = resolveSnowflakeAuth({ SNOWFLAKE_PAT: 'p', SNOWFLAKE_ACCOUNT: 'xy12345.eu-central-1' }, none)!;
    expect(pat.mode).toBe('PAT');
    expect(pat.host).toBe('xy12345.eu-central-1.snowflakecomputing.com');
    expect(await pat.headers()).toMatchObject({ Authorization: 'Bearer p', 'X-Snowflake-Authorization-Token-Type': 'PROGRAMMATIC_ACCESS_TOKEN' });
    const { privateKey } = generateKeyPairSync('rsa', { modulusLength: 2048 });
    const kp = resolveSnowflakeAuth({
      SNOWFLAKE_ACCOUNT: 'xy12345', SNOWFLAKE_USER: 'u', SNOWFLAKE_HOST: 'https://xy12345.snowflakecomputing.com/',
      SNOWFLAKE_PRIVATE_KEY: privateKey.export({ type: 'pkcs8', format: 'pem' }).toString(),
    }, none)!;
    expect(kp.mode).toBe('KEYPAIR_JWT');
    expect(kp.host).toBe('xy12345.snowflakecomputing.com');
    const h1 = await kp.headers();
    expect(h1['X-Snowflake-Authorization-Token-Type']).toBe('KEYPAIR_JWT');
    expect((await kp.headers()).Authorization).toBe(h1.Authorization); // cached

    // SPCS wins over everything and re-reads the rotating token file per request
    const dir = mkdtempSync(path.join(tmpdir(), 'kavach-spcs-'));
    const tokenFile = path.join(dir, 'token');
    writeFileSync(tokenFile, 'tok-1\n');
    const spcs = resolveSnowflakeAuth({ SNOWFLAKE_HOST: 'acct.snowflakecomputing.com', SNOWFLAKE_PAT: 'p' }, tokenFile)!;
    expect(spcs.mode).toBe('SPCS');
    expect(await spcs.headers()).toMatchObject({ Authorization: 'Bearer tok-1', 'X-Snowflake-Authorization-Token-Type': 'OAUTH' });
    writeFileSync(tokenFile, 'tok-2');
    expect((await spcs.headers()).Authorization).toBe('Bearer tok-2');
    rmSync(dir, { recursive: true, force: true });
  });
});
