-- =====================================================================
-- Kavach 00: roles, warehouse, database, schemas, stages
-- Run as ACCOUNTADMIN (trial / hackathon account).
-- =====================================================================
USE ROLE ACCOUNTADMIN;

-- KAVACH_ADMIN owns data + the immutable audit log.
-- KAVACH_APP   runs the Kavach API (NestJS on SPCS); read-only on data, cannot UPDATE/DELETE audit.
CREATE ROLE IF NOT EXISTS KAVACH_ADMIN;
CREATE ROLE IF NOT EXISTS KAVACH_APP;
GRANT ROLE KAVACH_APP   TO ROLE KAVACH_ADMIN;
GRANT ROLE KAVACH_ADMIN TO ROLE SYSADMIN;

SET MY_USER = CURRENT_USER();
GRANT ROLE KAVACH_ADMIN TO USER IDENTIFIER($MY_USER);
GRANT ROLE KAVACH_APP   TO USER IDENTIFIER($MY_USER);

CREATE WAREHOUSE IF NOT EXISTS KAVACH_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE KAVACH_WH TO ROLE KAVACH_ADMIN;
GRANT USAGE ON WAREHOUSE KAVACH_WH TO ROLE KAVACH_APP;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE KAVACH_ADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE KAVACH_ADMIN;   -- optional live-alert simulator

-- Cortex LLM functions, Cortex Analyst and Cortex Search
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE KAVACH_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE KAVACH_APP;

-- If your region does not host the chosen LLM, allow cross-region inference:
-- ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

USE ROLE KAVACH_ADMIN;
USE WAREHOUSE KAVACH_WH;

CREATE DATABASE IF NOT EXISTS KAVACH;
CREATE SCHEMA IF NOT EXISTS KAVACH.CORE      COMMENT = 'Synthetic loan, transaction, KYC and alert data';
CREATE SCHEMA IF NOT EXISTS KAVACH.KNOWLEDGE COMMENT = 'Policy / regulation corpus and Cortex Search service';
CREATE SCHEMA IF NOT EXISTS KAVACH.GOV       COMMENT = 'Immutable, hash-chained audit log and findings';
CREATE SCHEMA IF NOT EXISTS KAVACH.APP       COMMENT = 'Semantic model and app runtime objects';

CREATE FILE FORMAT IF NOT EXISTS KAVACH.CORE.CSV_FMT
  TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE NULL_IF = ('') TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

CREATE STAGE IF NOT EXISTS KAVACH.CORE.RAW_STAGE FILE_FORMAT = KAVACH.CORE.CSV_FMT;
CREATE STAGE IF NOT EXISTS KAVACH.APP.SEMANTIC_MODELS DIRECTORY = (ENABLE = TRUE);
CREATE STAGE IF NOT EXISTS KAVACH.KNOWLEDGE.RBI_PDFS DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') COMMENT = 'Optional: official RBI PDFs for PARSE_DOCUMENT ingestion';

-- ---------------- grants for the app role ----------------
GRANT USAGE ON DATABASE KAVACH TO ROLE KAVACH_APP;
GRANT USAGE ON ALL SCHEMAS IN DATABASE KAVACH TO ROLE KAVACH_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA KAVACH.CORE      TO ROLE KAVACH_APP;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA KAVACH.CORE      TO ROLE KAVACH_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA KAVACH.KNOWLEDGE TO ROLE KAVACH_APP;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA KAVACH.GOV       TO ROLE KAVACH_APP;
GRANT READ ON STAGE KAVACH.APP.SEMANTIC_MODELS TO ROLE KAVACH_APP;
GRANT CREATE STAGE     ON SCHEMA KAVACH.APP TO ROLE KAVACH_APP;
